### ISSUE TITLE
Doesn't work when VSC is connected to a DevContainer

### ISSUE THREAD

**Issue by alexdresko** [ChrisTowles/vscode-markdown-paste-image#1]
This extension works fine on my Windows machine when I've got a Windows folder opened as one normally would. But when I connect to a remote container (running Linux), I get "No image was found in the clipboard":

![image](https://user-images.githubusercontent.com/333022/196575687-76d5466a-1b3c-4535-ac80-e561a4c8a25c.png)

On one hand, I can see how this limitation would be obvious. But since I'm not smart enough to know one way or another, I figured I'd create this issue. 

Before that error, I was getting an error about needing to install xclip. So I `sudo apt update && sudo apt install xclip -y`, and then I started getting the error above. 

Interesting, I see some xclip related stuff in the code for this VSC plugin which also allows pasting images in MD. https://github.com/mushanshitiancai/vscode-paste-image

But that's all I know, really. I'm happy to provide more information if you'd like. Heck, you can pull my repo and "Open in Container" if you'd like to try the plugin in a dev container yourself. I don't know if that would help or not. 

Honestly, it would be very very cool if this did work on a dev container. Obviously, that's where I'm going to be spending the majority of my time, and this plugin works great otherwise.

**Comment by alexdresko** [comment]
Sorry, should have included a link to explain what dev containers are if you didn't know: https://code.visualstudio.com/docs/remote/containers

**Comment by ChrisTowles** [comment]
Thanks for the Issue, i'll try and give this a look
